
all: Colleen Grace Sully

re: fclean all

Colleen: Colleen.c
	gcc -Wall -Wextra -Werror Colleen.c -o Colleen
Grace: Grace.c
	gcc -Wall -Wextra -Werror Grace.c -o Grace
Sully: Sully.c
	gcc -Wall -Wextra -Werror Sully.c -o Sully
clean:
	rm -rf Colleen Grace Sully_0 Sully_1 Sully_2 Sully_3 Sully_4 Sully_5
fclean: clean
	rm -rf Grace_kid.c Sully Sully_*.c

