
all: Colleen Grace

re: fclean all

Colleen: Colleen.c
	gcc -Wall -Wextra -Werror Colleen.c -o Colleen

Grace: Grace.c
	gcc -Wall -Wextra -Werror Grace.c -o Grace

clean:
	rm -rf Colleen Grace
fclean: clean
	rm -rf Grace_kid.c
