
all: Colleen Grace Sully

re: fclean all

Colleen: Colleen.c
	gcc -Wall -Wextra -Werror Colleen.c -o Colleen
Grace: Grace.c
	gcc -Wall -Wextra -Werror Grace.c -o Grace
Sully: Sully.c
	mkdir SullyChilds
	gcc -Wall -Wextra -Werror Sully.c -o ./SullyChilds/Sully
clean:
	rm -rf Colleen Grace SullyChilds/Sully_0 SullyChilds/Sully_1 SullyChilds/Sully_2 SullyChilds/Sully_3 SullyChilds/Sully_4 SullyChilds/Sully_5
fclean: clean
	rm -rf Grace_kid.c SullyChilds

