
all: Colleen Grace Sully

re: fclean all

Colleen: Colleen.cpp
	g++ -Wall -Wextra -Werror Colleen.cpp -o Colleen
Grace: Grace.cpp
	g++ -Wall -Wextra -Werror Grace.cpp -o Grace
Sully: Sully.cpp
	g++ -Wall -Wextra -Werror Sully.cpp -o Sully
clean:
	rm -rf Colleen Grace Sully_0 Sully_1 Sully_2 Sully_3 Sully_4 Sully_5
fclean: clean
	rm -rf Grace_kid.cpp Sully Sully_*.cpp

